apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: cluster-identity
spec:
  text: "Cluster West — Test | EU-West-1"
  location: BannerTop
  color: "#008000"
  # GREEN
  backgroundColor: "#EE0000"
  # #008000 — web/HTML green
  # #3E8635 — Red Hat success green
  
