apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: maas-external
  namespace: llm
spec:
  hosts:
  - litellm-prod.apps.maas.redhatworkshops.io
  ports:
  - number: 443
    name: https
    protocol: HTTPS
  location: MESH_EXTERNAL
  resolution: DNS