apiVersion: v1
kind: Secret
metadata:
  name: llm-api-key-user1
  namespace: kuadrant-system
  labels:
    app: llm
  annotations:
    secret.kuadrant.io/user-id: user1
    upstream-authorization: "Bearer ${LLM_API_KEY}"
type: Opaque
stringData:
  api_key: my-own-custom-key