apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: kuadrant-system
---

apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:

  name: kuadrant-system
  namespace: kuadrant-system

spec:
  observability: {}
