# external-secret-namespace-a.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: aws-credentials
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: central-secret-store
    kind: ClusterSecretStore
  target:
    name: aws-credentials    # name of Secret created in this namespace
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aws-credentials  # copies all keys from the source secret