apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: istio-cni
spec: {}
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
spec:
  # update if using a different version of Istio
  version: v1.27.5
  namespace: istio-cni
