apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: istio-controlplane-patch.yaml
    target:
      kind: Istio
      name: default
  - path: namespace-patch.yaml
    target:
      kind: Namespace
      name: istio-system
