apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: bookinfo-rl
  namespace: bookinfo
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: bookinfo
    sectionName: rule-1
  defaults:
    strategy: merge
    limits:
      "bob-limit":
        rates:

        - limit: 20
          window: 10s
        when:
        - predicate: "auth.identity.userid == 'bob'"