apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: llm-route-rlp
  namespace: my-first-model
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: llm-route
  defaults:
    limits:
      route-rate-limit:
        rates:
          - limit: 20
            window: 10s
