# Istio control plane base; clusterName and network are set by overlays (east/west).
apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  version: v1.27.5
  namespace: istio-system
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: placeholder
      network: placeholder
    meshConfig:
      # only needed for travel-agency demo
      serviceSettings:
        - hosts:
            - cars.travel-agency.svc.cluster.local
            - flights.travel-agency.svc.cluster.local
            - hotels.travel-agency.svc.cluster.local
            - insurances.travel-agency.svc.cluster.local
            - discounts.travel-agency.svc.cluster.local
            - mysqldb.travel-agency.svc.cluster.local
          settings:
            clusterLocal: true
      discoverySelectors:
        - matchLabels:
            istio-injection: enabled
        - matchLabels:
            kubernetes.io/metadata.name: istio-system
        - matchLabels:
            istio-discovery: enabled
      # set defaultServiceExportTo: ["*"] for cross-cluster traffic between different namespaces
      # set defaultServiceExportTo: ["."] for cross-cluster traffic within the same namespace 
      defaultServiceExportTo: ["*"]
      defaultVirtualServiceExportTo: ["*"]
      defaultDestinationRuleExportTo: ["*"]
      trustDomain: cluster.local
